### ISSUE TITLE
Not working for some videos

### ISSUE THREAD

**Issue by unreleased** [goto-bus-stop/get-youtube-chapters#2]
Hi, wanted to report that I have found a video that this does not work on, however, it does work on YouTube.

https://www.youtube.com/watch?v=GHcWZfsmqsI

Thanks for the Library,
Conor

**Comment by goto-bus-stop** [comment]
thanks! it must be the [brackets]. maybe (parens) are also supported by youtube.

it should be a simple addition to one/some of the regexes, i can do it after work if i don't forget 🤠

**Comment by unreleased** [comment]
I'm going to be honest, I originally didn't have much hope that you would see the issue on this 2yo repo anyway. Thank you for doing this! I searched Github extremely hard yesterday for every JS solution and ripped them from a few different projects and everything seemed to fail at multiple edge cases (except this one, only one!)

**Comment by goto-bus-stop** [comment]
released as 📦 2.0.0
